import tkinter as tk
win=tk.Tk()
win.title("FORM")
win.geometry("500x500")
ln=tk.Label(win,text="STUDENT REGISTRATION FORM").grid(row=0,column=3)
l1=tk.Label(win,text="Enter Name:").grid(row=2,column=2)
l2=tk.Label(win,text="Enter Phno:").grid(row=4,column=2)
l3=tk.Label(win,text="Enter Email:").grid(row=6,column=2)
e1=tk.Entry(win,width=30).grid(row=2,column=3)
e2=tk.Entry(win,width=30).grid(row=4,column=3)
e3=tk.Entry(win,width=30).grid(row=6,column=3)
gp=tk.Label(win,text="Enter Group:").grid(row=8,column=2)
lb=tk.Listbox(win)
lb.insert(0,"---SELECT---")
lb.insert(1,"BSC")
lb.insert(2,"BCA")
lb.insert(3,"BCS-AI")
lb.insert(4,"BSC-DS")
lb.grid(row=10,column=3)
gn=tk.Label(win,text="Enter Gender:").grid(row=14,column=2)
v1=tk.IntVar()
tk.Radiobutton(win,text="Male",variable=v1,value=1).grid(row=16,column=3,sticky=tk.W)
tk.Radiobutton(win,text="Female",variable=v1,value=2).grid(row=18,column=3,sticky=tk.W)
course=tk.Label(win,text="Enter course:").grid(row=20,column=2)
c1=tk.IntVar()
tk.Checkbutton(win,text="python programming",variable=c1).grid(row=22,column=3,sticky=tk.W)
c2=tk.IntVar()
tk.Checkbutton(win,text="AI",variable=c2).grid(row=24,column=3,sticky=tk.W)
c3=tk.IntVar()
tk.Checkbutton(win,text="Cyber Security",variable=c3).grid(row=26,column=3,sticky=tk.W)
c4=tk.IntVar()
tk.Checkbutton(win,text="Block chain",variable=c4).grid(row=28,column=3,sticky=tk.W)
bt=tk.Button(win,text="Submit",width=20,activebackground="lightgreen").grid(row=32,column=3)
bt.pack()
c1.pack()
c2.pack()
c2.pack()
c4.pack()
lb.pack()
ln.pack()
l1.pack()
l2.pack()
l3.pack()
win.mainloop()

